# Generated by Django 3.2 on 2021-10-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, unique=True, verbose_name='адрес')),
                ('latitude', models.FloatField(null=True, verbose_name='широта')),
                ('longitude', models.FloatField(null=True, verbose_name='долгота')),
                ('coorinates_inserted', models.DateTimeField(auto_now=True, null=True, verbose_name='дата добавления координат')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
    ]
