# Generated by Django 3.2 on 2021-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20211009_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Заказ обработан?'),
        ),
    ]
