# Generated by Django 3.2 on 2021-10-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ОБРАБОТАН', 'Обработан'), ('НЕ ОБРАБОТАН', 'Не обработан')], default='НЕ ОБРАБОТАН', max_length=255, verbose_name='Статус заказа'),
        ),
    ]
