# Generated by Django 3.2 on 2021-10-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20211012_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
