# Generated by Django 3.2 on 2021-10-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20211014_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymenth_method',
            field=models.CharField(choices=[('ОНЛАЙН', 'Оплата онлайн'), ('НАЛИЧНЫЕ', 'Оплата наличными')], default='НАЛИЧНЫЕ', max_length=255, verbose_name='Способ оплаты'),
        ),
    ]
