# Generated by Django 3.2 on 2021-10-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_paymenth_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymenth_method',
            new_name='payment_method',
        ),
    ]
