# Generated by Django 3.2 on 2021-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ОНЛАЙН', 'Оплата онлайн'), ('НАЛИЧНЫЕ', 'Оплата наличными')], max_length=255, verbose_name='Способ оплаты'),
        ),
    ]
